export interface IUploadResult {
  upload_id: string;
  message: string;
}

export interface ISaveItemRequest {
  categories: string[];
  description: string;
  id: string;
  is_adult: boolean;
  is_editorial: boolean;
  is_illustration: boolean;
  keywords: string[];
  releases: any[];
  submitter_note: string;
}

export interface ISaveItemsResponse {
  success: number;
  saved: string[];
  notSaved: any[];
}

export interface ISubmitItemsRequest {
  media: ISubmitMedia[];
  keywords_not_to_spellcheck: string[];
  skip_spellcheck: string;
}

export interface ISubmitMedia {
  media_type: string;
  media_id: string;
}

// Generated by https://quicktype.io

export interface ISubmitItemsResponse {
  data: ISubmitItemsResponse;
}

export interface ISubmitItemsResponse {
  item_errors: any[];
  success: ISubmitItemResult[];
  first_submit_check: IFirstSubmitCheck;
}

export interface IFirstSubmitCheck {
  code: string;
  message: string;
  original_code: string;
}

export interface ISubmitItemResult {
  upload_id: string;
  media_id: number;
  media_type: string;
}

export interface IImagesToSubmitResponse {
  data: IImageInfo[];
  total_count: number;
  errors: IImageError[];
}

export interface IImageInfo {
  categories: any[];
  created: string;
  dependent_ids: any[];
  description: string;
  filename: string;
  height: number;
  id: string;
  is_adult: boolean;
  is_editorial: boolean;
  is_illustration: boolean;
  keywords: string[];
  media_type: string;
  original_filename: string;
  releases: any[];
  updated: string;
  uploaded_filename: string;
  watermark_placement: number;
  width: number;
  workflow_status: string;
  thumbnail_url: string;
  thumbnail_url_480: string;
  contributor_id: number;
}

export interface IImageError {
  id: string;
  message: IImageMessage;
}

export interface IImageMessage {
  filename: string;
  code: string;
  message: string;
}
